VPATH=@VPATH@

bindir = $(DESTDIR)@BINDIR@
asdir  = $(DESTDIR)@XDGCONFDIR@/autostart

INSTALL_DATA=@INSTALL_DATA@
INSTALL_BIN=@INSTALL_PROGRAM@
MKDIR=@INSTALL_DIR@
RM=rm

SCRIPTS = hp-autorotate
ASFILES = hp-autorotate.desktop

.PHONY: all install clean distclean

all: $(SCRIPTS)

install: all
	$(MKDIR) @BINDIR@ @XDGCONFDIR@/autostart
	$(INSTALL_BIN) $(SCRIPTS) @BINDIR@
	$(INSTALL_DATA) $(ASFILES) @XDGCONFDIR@/autostart

clean:
	$(RM) $(SCRIPTS)

distclean: clean
	$(RM) Makefile
